// Sentry is wired up outside this file — nothing to init in the layout:
//   • instrumentation.ts        — Node + edge runtimes
//   • instrumentation-client.ts — browser bundle
//   • lib/sentry-config.ts      — options shared by all three
//   • app/global-error.tsx      — root error boundary that reports crashes
// The extension reports to a separate Sentry project (clipmark-extension) so
// content-script noise from youtube.com can't drown out webapp issues.

import type { Metadata } from 'next';
import { Plus_Jakarta_Sans, Inter, JetBrains_Mono } from 'next/font/google';
import { Analytics } from '@vercel/analytics/next';
import './globals.css';
import { ThemeProvider } from './components/ThemeProvider';
import { APP_URL, CHROME_STORE_URL } from './lib/constants';
import { ogImageUrl } from './lib/seo';

// Site-wide fallback card: inherited by any route that doesn't build its own via
// buildPageMetadata(). Next REPLACES openGraph rather than merging it, so a route
// that sets a partial block loses this entirely — which is the bug app/lib/seo.ts
// exists to prevent.
const DEFAULT_OG_IMAGE = ogImageUrl({
  title: 'Turn YouTube Into Video Flashcards You Remember',
  subtitle: 'Bookmark the moment. Active Recall quizzes you before it replays.',
});

const plusJakarta = Plus_Jakarta_Sans({ 
  subsets: ['latin'], 
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-plus-jakarta' 
});
const inter = Inter({ 
  subsets: ['latin'], 
  weight: ['300', '400', '500', '600'],
  variable: '--font-inter' 
});
const jetbrains = JetBrains_Mono({ 
  subsets: ['latin'],
  variable: '--font-jetbrains' 
});

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: 'ClipMark — YouTube Timestamp Bookmarks',
  description: 'Bookmark YouTube moments, get AI summaries, and revisit key insights — free Chrome extension for students, developers, and creators.',
  keywords: ['youtube bookmarks', 'youtube timestamp', 'youtube notes', 'chrome extension', 'ai summarizer', 'spaced repetition', 'study help'],
  // Generated by scripts/generate-icons.py from public/clipmark-logo.png. Before
  // this the only icon was that raw 450×450 logo, so /favicon.ico — which
  // browsers request whether or not you link one — returned a 404, and iOS had
  // nothing to use for a home-screen tile.
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: '16x16 32x32 48x48' },
      { url: '/icon-192.png', type: 'image/png', sizes: '192x192' },
      { url: '/icon-512.png', type: 'image/png', sizes: '512x512' },
    ],
    shortcut: '/favicon.ico',
    apple: { url: '/apple-touch-icon.png', sizes: '180x180' },
  },
  alternates: {
    canonical: '/',
  },
  verification: {
    google: 'chJnY3idU4qZvir3ZZ3NAcVF3mde32n0AMYk2SJNt1k',
  },
  openGraph: {
    title: 'ClipMark — YouTube Timestamp Bookmarks',
    description: 'Bookmark YouTube moments, get AI summaries, and revisit key insights. Free Chrome extension.',
    type: 'website',
    url: APP_URL,
    siteName: 'ClipMark',
    images: [
      {
        url: DEFAULT_OG_IMAGE,
        width: 1200,
        height: 630,
        alt: 'ClipMark — YouTube Timestamp Bookmarks',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'ClipMark — YouTube Timestamp Bookmarks',
    description: 'Bookmark YouTube moments, get AI summaries, and revisit key insights. Free Chrome extension.',
    images: [DEFAULT_OG_IMAGE],
  },
};

// Inline script runs synchronously before first paint to avoid flash of wrong theme.
const themeScript = `
  try {
    var t = localStorage.getItem('theme');
    if (t === 'dark') document.documentElement.setAttribute('data-theme', 'dark');
  } catch(e) {}
`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    'name': 'ClipMark',
    'operatingSystem': 'ChromeOS, Windows, macOS, Linux',
    'applicationCategory': 'EducationalApplication, BrowserExtension',
    'installUrl': CHROME_STORE_URL,
    'offers': {
      '@type': 'Offer',
      'price': '0',
      'priceCurrency': 'USD',
    },
  };

  return (
    <html lang="en" data-theme="light" className={`${plusJakarta.variable} ${inter.variable} ${jetbrains.variable}`}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {/* eslint-disable-next-line @next/next/no-before-interactive-script-outside-document */}
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        {/* Material Symbols is self-hosted from /public/fonts (see the @font-face
            in globals.css) — the text families already come from next/font, which
            serves them off our own origin, so no font is fetched from Google at
            runtime. Preloaded because icons appear above the fold in the nav. */}
        <link
          rel="preload"
          href="/fonts/material-symbols-outlined.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
        {/* Vercel Web Analytics — visitor/page-view counts for the marketing site.
            Cookieless and aggregate-only, so it needs no consent banner, and it is
            unrelated to the extension's own feature-usage instrumentation.

            No data flows until Analytics is switched on for the project in the
            Vercel dashboard (Project → Analytics → Enable); off, the script is a
            no-op. It also only reports from Vercel deployments — `next dev` and
            `next start` runs are ignored, so a local build showing nothing is
            expected, not a misconfiguration. */}
        <Analytics />
      </body>
    </html>
  );
}
